# Generated by Django 6.0.1 on 2026-04-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0003_periodtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'classroom_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('building_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_restricted', models.IntegerField()),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('universities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
                ('classroom_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.classroomtypes')),
            ],
            options={
                'db_table': 'classrooms',
                'managed': True,
            },
        ),
    ]
