# Generated by Django 6.0.1 on 2026-04-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('building_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_restricted', models.IntegerField()),
                ('is_restricted_to_subjects', models.IntegerField()),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'classrooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassroomSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'classroom_subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassroomTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'classroom_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassroomCareers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('careers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers')),
            ],
            options={
                'db_table': 'classroom_careers',
                'managed': True,
            },
        ),
    ]
