
# Generated by Django 6.0.1 on 2026-04-04 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_groups'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCareers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('careers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers')),
                ('classrooms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.classrooms')),
            ],
            options={
                'db_table': 'classroom_careers',
                'managed': True,
            },
        ),
    ]
