# Generated by Django 6.0.1 on 2026-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_classroom_subject_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='is_restricted_to_subjects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroomsubjects',
            name='is_deleted',
            field=models.IntegerField(),
        ),
    ]
