# Generated by Django 6.0.1 on 2026-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('hex', models.CharField(max_length=6)),
                ('contrast_hex', models.CharField(max_length=6)),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100, blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=100, blank=True, null=True)),
            ],
            options={
                'db_table': 'colors',
                'managed': True,
            },
        ),
    ]
