# Generated by Django 6.0.1 on 2026-04-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_initial'),
        ('subjects', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
        migrations.AddField(
            model_name='subjectsclassroomtypes',
            name='classroom_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.classroomtypes'),
        ),
        migrations.AddField(
            model_name='subjectsclassroomtypes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subjects'),
        ),
    ]
