# Generated by Django 6.0.1 on 2026-03-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='is_deleted',
            field=models.IntegerField(),
        ),
    ]
