# Generated by Django 6.0.1 on 2026-03-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_colors_is_deleted'),
        ('universities', '0002_seed_utez_selected_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('hours_per_week', models.IntegerField()),
                ('is_mandatory', models.IntegerField()),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.colors')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'subjects',
                'managed': True,
            },
        ),
    ]
