# Generated by Django 6.0.1 on 2026-04-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroomcareers'),
        ('subjects', '0003_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='is_restricted_to_classroom_types',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubjectsClassroomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.classroomtypes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subjects')),
            ],
            options={
                'db_table': 'subjects_classroom_types',
                'managed': True,
            },
        ),
    ]
