# Generated by Django 6.0.1 on 2026-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='is_restricted_to_classroom_types',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectsclassroomtypes',
            name='is_deleted',
            field=models.IntegerField(),
        ),
    ]
