# Generated by Django 6.0.1 on 2026-04-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0007_images_universities_uses_period_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('data', models.JSONField()),
                ('assigned_count', models.IntegerField()),
                ('unassigned_count', models.IntegerField()),
                ('is_confirmed', models.IntegerField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.academicperiods')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'schedule_versions',
                'managed': True,
            },
        ),
    ]
