# Generated by Django 6.0.1 on 2026-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('data', models.JSONField()),
                ('assigned_count', models.IntegerField()),
                ('unassigned_count', models.IntegerField()),
                ('is_confirmed', models.IntegerField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'schedule_versions',
                'managed': True,
            },
        ),
    ]
