# Generated by Django 6.0.1 on 2026-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleversions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
