from .universities import UniversityCreate, UniversityList, UniversityDetail
from .period_types import PeriodTypesSelectView
from .academic_periods import AcademicPeriodListCreateView, AcademicPeriodDetailView, AcademicPeriodToggleStatusView
from .shifts import ShiftDetailView, ShiftListView
from .full_universities import UniversityFullSetupView