from .universities import UniversityCreate, UniversityList, UniversityDetail
from .period_types import PeriodTypesSelectView
from .academic_periods import AcademicPeriodListCreateView, AcademicPeriodDetailView, AcademicPeriodToggleStatusView