# Generated by Django 6.0.1 on 2026-04-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifts',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
        migrations.AddField(
            model_name='academicperiods',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
        migrations.AddField(
            model_name='universityclassroomtypepriorities',
            name='classroom_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.classroomtypes'),
        ),
        migrations.AddField(
            model_name='universityclassroomtypepriorities',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
    ]
