# Generated by Django 6.0.1 on 2026-04-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_periodtypes'),
    ]

    operations = []
