# Generated by Django 6.0.1 on 2026-04-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_academicperiods_shifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiods',
            options={'managed': False},
        ),
    ]
