# Generated by Django 6.0.1 on 2026-04-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_seed_period_types_and_academic_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='uses_period_groups',
            field=models.BooleanField(default=False),
        ),
    ]
