# Generated by Django 6.0.1 on 2026-04-05 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_seed_period_types_and_academic_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=45)),
                ('mime_type', models.CharField(max_length=45)),
                ('extension', models.CharField(max_length=10)),
                ('sha256', models.CharField(max_length=64)),
                ('file_size', models.IntegerField()),
                ('image_path', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='universities',
            name='uses_period_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='universities',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.images'),
        ),
    ]
