# Generated by Django 6.0.1 on 2026-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_universities_period_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='is_deleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='uses_period_groups',
            field=models.IntegerField(),
        ),
    ]
