# Generated by Django 6.0.1 on 2026-04-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_alter_classrooms_is_restricted_to_subjects_and_more'),
        ('universities', '0009_alter_images_created_at_alter_images_is_deleted_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        CREATE TABLE IF NOT EXISTS university_classroom_type_priorities (
                            id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            university_id BIGINT NOT NULL,
                            classroom_type_id BIGINT NOT NULL,
                            priority INT NOT NULL,
                            is_deleted INT NOT NULL,
                            created_at DATETIME NULL,
                            created_by VARCHAR(100) NULL,
                            updated_at DATETIME NULL,
                            updated_by VARCHAR(100) NULL,
                            INDEX idx_uctp_university_id (university_id),
                            INDEX idx_uctp_classroom_type_id (classroom_type_id),
                            CONSTRAINT fk_uctp_university
                                FOREIGN KEY (university_id)
                                REFERENCES universities (id)
                                ON DELETE NO ACTION
                                ON UPDATE NO ACTION,
                            CONSTRAINT fk_uctp_classroom_type
                                FOREIGN KEY (classroom_type_id)
                                REFERENCES classroom_types (id)
                                ON DELETE NO ACTION
                                ON UPDATE NO ACTION
                        );
                    ''',
                    reverse_sql='DROP TABLE IF EXISTS university_classroom_type_priorities;',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='UniversityClassroomTypePriorities',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('priority', models.IntegerField()),
                        ('is_deleted', models.IntegerField()),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                        ('updated_at', models.DateTimeField(blank=True, null=True)),
                        ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                        ('classroom_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classrooms.classroomtypes')),
                        ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
                    ],
                    options={
                        'db_table': 'university_classroom_type_priorities',
                        'managed': True,
                    },
                ),
            ],
        ),
    ]
