# Generated by Django 6.0.1 on 2026-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_university_classroom_type_priorities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiods',
            options={'managed': True},
        ),
    ]
