# Generated by Django 6.0.1 on 2026-04-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersuniversities',
            name='universities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
    ]
