# Generated by Django 6.0.1 on 2026-03-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_align_teachers_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teachers')),
            ],
            options={
                'db_table': 'teacher_availabilities',
                'managed': True,
            },
        ),
    ]
