# Generated by Django 6.0.1 on 2026-04-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_availabilities'),
        ('teachers', '0004_teacherssubjects'),
    ]

    operations = [
    ]
