# Generated by Django 6.0.1 on 2026-04-03 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_merge_20260331_2301'),
        ('universities', '0005_alter_academicperiods_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersUniversities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teachers')),
                ('universities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'teachers_universities',
                'managed': True,
            },
        ),
    ]
