# Generated by Django 6.0.1 on 2026-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teachersuniversities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherssubjects',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='teacheravailabilities',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
