"""
Django settings for horarios_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging.config
from pathlib import Path
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
from loguru import logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: mantén la clave secreta fuera del control de versiones en producción.
SECRET_KEY = os.getenv('SECRET_KEY')

# ADVERTENCIA DE SEGURIDAD: no actives DEBUG en producción.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

_allowed = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [s.strip() for s in _allowed.split(',') if s.strip()]


# Definición de aplicaciones

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'user_accounts',
    'subjects',
    'universities',
    'careers',
    'teachers',
    'classrooms',
    'audit',
    'schedule_generator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Permitir solicitudes CORS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'horarios_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'horarios_backend.wsgi.application'


# CORS
# https://pypi.org/project/django-cors-headers/

_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [s.strip() for s in _cors_origins.split(',') if s.strip()]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-encrypted',
]


# Base de datos
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Validación de contraseñas
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user_accounts.User'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

PASSWORD_HASHERS = [ # Usar bcrypt para encriptar contraseñas
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Fallback para contraseñas antiguas
]

REST_FRAMEWORK = { # Configuración de Django REST Framework
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exception_handler.custom_exception_handler', # Manejo global de excepciones personalizado
}

SPECTACULAR_SETTINGS = { # Configuración de drf-spectacular para documentación OpenAPI
    'TITLE': 'Sistema de Generación de Horarios Académicos',
    'DESCRIPTION': 'API para la gestión y generación de horarios académicos',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'jwtAuth': []}],
    'COMPONENT_SPLIT_REQUEST': True,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # minutes=30
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}


# Internacionalización
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/'media'


## Configuración de logging con Loguru
LOGGING_CONFIG = None

fmt = "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"


def _is_swagger_noise(record):
    """Ignora trazas de depuracion relacionadas con Swagger/OpenAPI."""
    logger_name = (record.get('name') or '').lower()
    message = str(record.get('message') or '').lower()
    swagger_markers = ('drf_spectacular', '/api/schema', '/swagger', 'openapi')
    return any(marker in logger_name or marker in message for marker in swagger_markers)

LOGURU_LOGGING = {
    'handlers': [
        {
            'sink': str(BASE_DIR / 'logs/debug/debug_{time:YYYY-MM-DD}.log'),
            'level': 'DEBUG',
            'filter': lambda record: record['level'].name == 'DEBUG' and not _is_swagger_noise(record),
            'format': fmt,
            'rotation': '00:00',
            'retention': '7 days',
            'compression': 'zip',
        },
        {
            'sink': str(BASE_DIR / 'logs/info/info_{time:YYYY-MM-DD}.log'),
            'level': 'INFO',
            'filter': lambda record: record['level'].name == 'INFO',
            'format': fmt,
            'rotation': '00:00',
            'retention': '30 days',
            'compression': 'zip',
        },
        {
            'sink': str(BASE_DIR / 'logs/warning/warning_{time:YYYY-MM-DD}.log'),
            'level': 'WARNING',
            'filter': lambda record: record['level'].name == 'WARNING',
            'format': fmt,
            'rotation': '00:00',
            'retention': '30 days',
            'compression': 'zip',
        },
        {
            'sink': str(BASE_DIR / 'logs/error/error_{time:YYYY-MM-DD}.log'),
            'level': 'ERROR',
            'filter': lambda record: record['level'].name == 'ERROR',
            'format': fmt,
            'rotation': '00:00',
            'retention': '90 days',
            'compression': 'zip',
            'backtrace': True,
            'diagnose': True,
        },
        {
            'sink': str(BASE_DIR / 'logs/error/error_{time:YYYY-MM-DD}.log'),
            'level': 'CRITICAL',
            'filter': lambda record: record['level'].name == 'CRITICAL',
            'format': fmt,
            'rotation': '00:00',
            'retention': '90 days',
            'compression': 'zip',
            'backtrace': True,
            'diagnose': True,
        },
    ]
}

# Crear directorios de logs si no existen
for log_subdir in ('debug', 'info', 'warning', 'error'):
    (BASE_DIR / 'logs' / log_subdir).mkdir(parents=True, exist_ok=True)

logger.configure(**LOGURU_LOGGING)

# Interceptar logs de Django y redirigirlos a Loguru
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'loguru': {
            'class': 'horarios_backend.interceptor.InterceptorHandler'
        }
    },
    'root': {
        'handlers': ['loguru'],
        'level': 'DEBUG'
    }
}

logging.config.dictConfig(LOGGING)
