# Generated by Django 6.0.1 on 2026-03-01 23:04

from django.db import migrations


def seed_users(apps, schema_editor):
    Role = apps.get_model('user_accounts', 'Role')
    User = apps.get_model('user_accounts', 'User')

    role_admin, _ = Role.objects.get_or_create(name='admin')
    role_user, _ = Role.objects.get_or_create(name='usuario')

    # Importar el hasher en tiempo de ejecución para respetar PASSWORD_HASHERS
    from django.contrib.auth.hashers import make_password

    users = [
        {
            'email': 'admin@gmail.com',
            'password': 'Admin123',
            'name': 'Admin',
            'surname': 'Sistema',
            'last_name': 'Horarios',
            'role': role_admin,
            'status': 1,
        },
        {
            'email': 'usuario@gmail.com',
            'password': 'Usuario123',
            'name': 'Usuario',
            'surname': 'Sistema',
            'last_name': 'Horarios',
            'role': role_user,
            'status': 1,
        },
    ]

    for data in users:
        if not User.objects.filter(email=data['email']).exists():
            data['password'] = make_password(data['password'])
            User.objects.create(**data)


def reverse_seed_users(apps, schema_editor):
    User = apps.get_model('user_accounts', 'User')
    User.objects.filter(email__in=[
        'admin@gmail.com',
        'usuario@gmail.com',
    ]).delete()


class Migration(migrations.Migration):
    
    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_users, reverse_seed_users),
    ]
    
