# Generated by Django 6.0.1 on 2026-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_userconfiguration_schedule_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfiguration',
            name='accent',
            field=models.CharField(db_comment='el color de la interfaz, ejemplo, rojo, verde, azul', max_length=10),
        ),
        migrations.AlterField(
            model_name='userconfiguration',
            name='theme',
            field=models.CharField(db_comment='El tema de la aplicación, ya sea oscuro (dark) o blanco (light)', max_length=10),
        ),
    ]
