sonar.projectKey=sonar-prueba-d
sonar.projectName=sonar-prueba-d
sonar.projectVersion=1.0

# Codigo fuente Python del proyecto
sonar.sources=core,horarios_backend,subjects,universities,user_accounts,teachers
sonar.sourceEncoding=UTF-8

# Analizar solo archivos Python
sonar.inclusions=**/*.py

# Excluir artefactos no relevantes
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc,**/node_modules/**,**/static/**

# Tests (subcarpetas existentes en tu proyecto)
sonar.tests=.
sonar.test.inclusions=**/tests/**/*.py,**/test_*.py