# Generated by Django 6.0.1 on 2026-03-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0002_seed_utez_selected_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('require_classroom', models.IntegerField()),
                ('status', models.IntegerField()),
                ('configurations', models.JSONField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'modalities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_periods', models.IntegerField()),
                ('status', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.modalities')),
            ],
            options={
                'db_table': 'careers',
                'managed': True,
            },
        ),
    ]
