# Generated by Django 6.0.1 on 2026-04-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('subjects', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
        migrations.AddField(
            model_name='careerperiodexceptions',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers'),
        ),
        migrations.AddField(
            model_name='careersubjects',
            name='careers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers'),
        ),
        migrations.AddField(
            model_name='careersubjects',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subjects'),
        ),
        migrations.AddField(
            model_name='groups',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.academicperiods'),
        ),
        migrations.AddField(
            model_name='groups',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers'),
        ),
        migrations.AddField(
            model_name='groups',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.shifts'),
        ),
        migrations.AddField(
            model_name='groups',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
        migrations.AddField(
            model_name='modalities',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities'),
        ),
        migrations.AddField(
            model_name='careers',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.modalities'),
        ),
        migrations.AddField(
            model_name='careers',
            name='parent_career',
            field=models.ForeignKey(blank=True, db_column='parent_career_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers'),
        ),
    ]
