# Generated by Django 6.0.1 on 2026-04-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_careersubjects'),
        ('universities', '0004_academicperiods_shifts'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Groups',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=45)),
                        ('period_number', models.IntegerField()),
                        ('letter', models.CharField(max_length=1)),
                        ('status', models.IntegerField()),
                        ('is_deleted', models.IntegerField()),
                        ('created_at', models.DateTimeField(blank=True, null=True)),
                        ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                        ('updated_at', models.DateTimeField(blank=True, null=True)),
                        ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                        ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.academicperiods')),
                        ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='careers.careers')),
                        ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.shifts')),
                        ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
                    ],
                    options={
                        'db_table': 'groups',
                        'managed': True,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
